local opt = vim.opt -- to set options

opt.autowriteall = true
opt.clipboard = "unnamedplus"
opt.completeopt = "menu,menuone,noselect"
opt.cursorline = true
opt.expandtab = true
opt.filetype = "on"
opt.guicursor = ""
opt.linebreak = true
opt.number = true
opt.relativenumber = true
opt.shiftwidth = 4
opt.showbreak = " +++ "
opt.showmatch = true
opt.showmode = false
opt.smartcase = true
opt.smartindent = true
opt.softtabstop = 4
opt.tabstop = 4
opt.termguicolors = true
opt.timeoutlen = 500
opt.wrap = false
