# Alacritty Configuration
# Version: 0.13+

# ==============================================================================
# SHELL & ENVIRONMENT
# ==============================================================================

[env]
TERM = "xterm-256color"

[terminal]
osc52 = "CopyPaste"  # Enable OSC 52 for clipboard operations

[terminal.shell]
program = "/bin/zsh"
args = ["-l", "-c", "/opt/homebrew/bin/tmux attach -t def 2>/dev/null || /opt/homebrew/bin/tmux new -s def; exec zsh"]

# ==============================================================================
# WINDOW CONFIGURATION
# ==============================================================================

[window]
decorations = "buttonless"
opacity = 1.0
blur = false
dimensions = { columns = 86, lines = 50 }
position = { x = 1425, y = 65 }
padding = { x = 16, y = 16 }
dynamic_padding = true
resize_increments = false
startup_mode = "Windowed"
title = "Alacritty"
dynamic_title = true

# ==============================================================================
# FONT CONFIGURATION
# ==============================================================================

[font]
size = 13.0
builtin_box_drawing = true
offset = { x = 0, y = 2 }

[font.normal]
family = "Liga SFMono Nerd Font"
style = "Light"

[font.bold]
family = "Liga SFMono Nerd Font"
style = "Regular"

[font.italic]
family = "Liga SFMono Nerd Font"
style = "Light Italic"

[font.bold_italic]
family = "Liga SFMono Nerd Font"
style = "Regular Italic"

# ==============================================================================
# CURSOR CONFIGURATION
# ==============================================================================

[cursor]
blink_interval = 750
blink_timeout = 5
unfocused_hollow = true
thickness = 0.15

[cursor.style]
shape = "Underline"
blinking = "On"

[cursor.vi_mode_style]
shape = "Underline"
blinking = "Off"

# ==============================================================================
# TERMINAL BEHAVIOR
# ==============================================================================

[scrolling]
history = 10000
multiplier = 3

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = true

# ==============================================================================
# COLOR SCHEME - Tokyo Night Moon
# ==============================================================================

# Default colors
[colors.primary]
background = '#222436'
foreground = '#c8d3f5'

# Normal colors
[colors.normal]
black = '#1b1d2b'
red = '#ff757f'
green = '#c3e88d'
yellow = '#ffc777'
blue = '#82aaff'
magenta = '#c099ff'
cyan = '#86e1fc'
white = '#828bb8'

# Bright colors
[colors.bright]
black = '#444a73'
red = '#ff8d94'
green = '#c7fb6d'
yellow = '#ffd8ab'
blue = '#9ab8ff'
magenta = '#caabff'
cyan = '#b2ebff'
white = '#c8d3f5'

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = '#ff966c'

[[colors.indexed_colors]]
index = 17
color = '#c53b53'

# ==============================================================================
# KEYBOARD BINDINGS
# ==============================================================================

[keyboard]

bindings = [
  { key = "Key0", mods = "Command", action = "ResetFontSize" },
  { key = "Equals", mods = "Command", action = "IncreaseFontSize" },
  { key = "Plus", mods = "Command", action = "IncreaseFontSize" },
  { key = "NumpadAdd", mods = "Command", action = "IncreaseFontSize" },
  { key = "Minus", mods = "Command", action = "DecreaseFontSize" },
  { key = "NumpadSubtract", mods = "Command", action = "DecreaseFontSize" },
  { key = "Left", mods = "Alt", chars = "\u001bb" },
  { key = "Right", mods = "Alt", chars = "\u001bf" },
  { key = "A", mods = "Alt", chars = "\u001ba" },
  { key = "B", mods = "Alt", chars = "\u001bb" },
  { key = "C", mods = "Alt", chars = "\u001bc" },
  { key = "D", mods = "Alt", chars = "\u001bd" },
  { key = "F", mods = "Alt", chars = "\u001bf" },
  { key = "R", mods = "Alt", chars = "\u001br" },
  { key = "V", mods = "Alt", chars = "\u001bv" },
  { key = "W", mods = "Alt", chars = "\u001bw" },
  { key = "Slash", mods = "Control", chars = "\u001f" },
  { key = "H", mods = "Control", chars = "\u001f" }
]

# ==============================================================================
# MOUSE CONFIGURATION
# ==============================================================================

[mouse]
hide_when_typing = true
bindings = [
  { mouse = "Right", action = "PasteSelection" }
]

# ==============================================================================
# BELL CONFIGURATION
# ==============================================================================

[bell]
animation = "EaseOutExpo"
duration = 0
color = "#ffffff"
command = "None"

# ==============================================================================
# DEBUG (useful for troubleshooting)
# ==============================================================================

[debug]
render_timer = false
persistent_logging = false
log_level = "Warn"
print_events = false
highlight_damage = false
prefer_egl = false
