[window]
decorations = "buttonless"
dimensions = { columns = 126, lines = 40 }
dynamic_padding = true
padding = { x = 16, y = 16 }

[[keyboard.bindings]]
chars = "\u001Bb"
key = "B"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bc"
key = "C"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bd"
key = "D"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "F"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Br"
key = "R"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bv"
key = "V"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bw"
key = "W"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001F"
key = "Slash"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001F"
key = "H"
mods = "Control"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "NumpadAdd"
mods = "Command"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Command"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "NumpadSubtract"
mods = "Command"

[terminal]

[colors.bright]
black = "0x4f5666"
blue = "0x4dc4ff"
cyan = "0x4cd1e0"
green = "0xa5e075"
magenta = "0xde73ff"
red = "0xff616e"
white = "0xe6e6e6"
yellow = "0xf0a45d"

[colors.normal]
black = "0x3f4451"
blue = "0x4aa5f0"
cyan = "0x42b3c2"
green = "0x8cc265"
magenta = "0xc162de"
red = "0xe05561"
white = "0xd7dae0"
yellow = "0xd18f52"

[colors.primary]
background = "0x282c34"
foreground = "0xabb2bf"

[cursor]
style = { blinking = "On", shape = "Underline" }
vi_mode_style = { shape = "Underline" }

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.bold]
style = "Semibold"

[font.normal]
family = "SF Mono"
style = "Regular"

[font.offset]
y = 2

[terminal.shell]
program = "/bin/zsh"
args = ["-l", "-c", "tmux attach -t def 2>/dev/null || tmux new -s def; exec zsh"]