[[keyboard.bindings]]
chars = "\u001Bb"
key = "B"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bc"
key = "C"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bd"
key = "D"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "F"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Br"
key = "R"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bv"
key = "V"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bw"
key = "W"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001F"
key = "Slash"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001F"
key = "H"
mods = "Control"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "NumpadAdd"
mods = "Command"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Command"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "NumpadSubtract"
mods = "Command"

[terminal]

[colors.bright]
black = "0x4f5666"
blue = "0x4dc4ff"
cyan = "0x4cd1e0"
green = "0xa5e075"
magenta = "0xde73ff"
red = "0xff616e"
white = "0xe6e6e6"
yellow = "0xf0a45d"

[colors.normal]
black = "0x3f4451"
blue = "0x4aa5f0"
cyan = "0x42b3c2"
green = "0x8cc265"
magenta = "0xc162de"
red = "0xe05561"
white = "0xd7dae0"
yellow = "0xd18f52"

[colors.primary]
background = "0x282c34"
foreground = "0xabb2bf"

[cursor]
vi_mode_style = "Underline"

[cursor.style]
blinking = "On"
shape = "Underline"

[env]
TERM = "xterm-256color"

[font]
size = 13.0

[font.bold]
style = "Semibold"

[font.normal]
family = "SF Mono"
style = "Regular"

[font.offset]
y = 2

[schemes.one-dark.bright]
black = "0x4f5666"
blue = "0x4dc4ff"
cyan = "0x4cd1e0"
green = "0xa5e075"
magenta = "0xde73ff"
red = "0xff616e"
white = "0xe6e6e6"
yellow = "0xf0a45d"

[schemes.one-dark.normal]
black = "0x3f4451"
blue = "0x4aa5f0"
cyan = "0x42b3c2"
green = "0x8cc265"
magenta = "0xc162de"
red = "0xe05561"
white = "0xd7dae0"
yellow = "0xd18f52"

[schemes.one-dark.primary]
background = "0x282c34"
foreground = "0xabb2bf"

[schemes.tokyo-night.bright]
black = "0x444b6a"
blue = "0x7da6ff"
cyan = "0x0db9d7"
green = "0xb9f27c"
magenta = "0xbb9af7"
red = "0xff7a93"
white = "0xacb0d0"
yellow = "0xff9e64"

[schemes.tokyo-night.normal]
black = "0x32344a"
blue = "0x7aa2f7"
cyan = "0x449dab"
green = "0x9ece6a"
magenta = "0xad8ee6"
red = "0xf7768e"
white = "0x787c99"
yellow = "0xe0af68"

[schemes.tokyo-night.primary]
background = "0x1a1b26"
foreground = "0xa9b1d6"

[schemes.tokyo-night-storm.bright]
black = "0x444b6a"
blue = "0x7da6ff"
cyan = "0x0db9d7"
green = "0xb9f27c"
magenta = "0xbb9af7"
red = "0xff7a93"
white = "0xacb0d0"
yellow = "0xff9e64"

[schemes.tokyo-night-storm.normal]
black = "0x32344a"
blue = "0x7aa2f7"
cyan = "0x449dab"
green = "0x9ece6a"
magenta = "0xad8ee6"
red = "0xf7768e"
white = "0x9699a8"
yellow = "0xe0af68"

[schemes.tokyo-night-storm.primary]
background = "0x24283b"
foreground = "0xa9b1d6"

[terminal.shell]
args = ["-l", "-c", "tmux attach -t default || tmux new -s default"]
program = "/bin/zsh"

[window]
decorations = "buttonless"
dynamic_padding = true

[window.dimensions]
columns = 138
lines = 46

[window.padding]
x = 20
y = 20